### ISSUE TITLE
How to hide in push

### ISSUE THREAD

**Issue by greezi** [chrishoste/printerest-tabbar#1]
Thank you for your hard work,
How to hide tabbar in push.

**Comment by chrishoste** [comment]
Hello greezi, 
I'm not quite sure what you meant by "push", I assumed that you meant to push a new ViewController onto the NavigationController. Please, correct me if I'm wrong. I added a toggle/hide function you can call whenever you need it. Let me know if I could help you with that. Just check out the GIF on the README :D

**Comment by greezi** [comment]
Hello chrishoste,
Thank you very much.
’push‘ is push a new ViewController onto the NavigationController.
But I found a problem. Canceling the return will appear on the controller that has been pushed.

<img width="374" alt="WX20200501-182116@2x" src="https://user-images.githubusercontent.com/13515835/80799123-9a87a880-8bd8-11ea-974e-ac7deb5491a4.png">

**Comment by chrishoste** [comment]
What do you mean by 'Canceling the return'

**Comment by greezi** [comment]
Sorry , Forgive me for my poor English。
I recorded a video： https://youtu.be/XUNy5ZWrHu4

**Comment by chrishoste** [comment]
Ah no, don't worry :D Good catch! Should be fixed 😅

**Comment by greezi** [comment]
Thank you, friend. Take care of yourself and your family during the outbreak of the epidemic.
I also found a fun set of animations 😁
![image_processing20191222-24289-gpzbrd](https://user-images.githubusercontent.com/13515835/80815182-bc485600-8bff-11ea-8bd6-596515361c3d.gif)

**Comment by chrishoste** [comment]
Thanks, you too 😄
